### ISSUE TITLE
通讯录界面会出现segfault

### ISSUE THREAD

**Issue by xiangzhai** [xiangzhai/qwx#15]
* Linux archlinux 3.19.2-1-ARCH
* Using Qt version 5.4.1
* GLib 2.42.2

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6bea8b9 in QV4::QObjectWrapper::wrap(QV4::ExecutionEngine*, QObject*) ()
   from /usr/lib/libQt5Qml.so.5
(gdb) bt
#0  0x00007ffff6bea8b9 in QV4::QObjectWrapper::wrap(QV4::ExecutionEngine*, QObject*) ()
   from /usr/lib/libQt5Qml.so.5
#1  0x00007ffff6cb3a0c in QV8Engine::fromVariant(QVariant const&) () from /usr/lib/libQt5Qml.so.5
#2  0x00007ffff6beaec2 in ?? () from /usr/lib/libQt5Qml.so.5
#3  0x00007ffff6bec09d in QV4::QObjectWrapper::getProperty(QObject*, QV4::ExecutionContext*, QQmlPropertyData*, bool) () from /usr/lib/libQt5Qml.so.5
#4  0x00007ffff6bec9c6 in QV4::QObjectWrapper::getQmlProperty(QV4::ExecutionContext*, QQmlContextData*, QV4::String*, QV4::QObjectWrapper::RevisionMode, bool*, bool) ()
   from /usr/lib/libQt5Qml.so.5
#5  0x00007ffff6becd17 in QV4::QObjectWrapper::getQmlProperty(QV4::ExecutionContext*, QQmlContextData*, QObject*, QV4::String*, QV4::QObjectWrapper::RevisionMode, bool*) ()
   from /usr/lib/libQt5Qml.so.5
#6  0x00007ffff6ca3a10 in QV4::QmlContextWrapper::get(QV4::Managed*, QV4::String*, bool*) ()
   from /usr/lib/libQt5Qml.so.5
#7  0x00007ffff6b7fa7a in QV4::ExecutionContext::getProperty(QV4::String*) ()
   from /usr/lib/libQt5Qml.so.5
#8  0x00007fffe89f9d2a in ?? ()
#9  0x00007fffffffdc9c in ?? ()
#10 0x00007fffffffdc80 in ?? ()
#11 0x0003000000000000 in ?? ()
#12 0x00007fffe8c36058 in ?? ()
#13 0x00007fffe8c26000 in ?? ()
#14 0x0000000000739480 in ?? ()
#15 0x0000000000739480 in ?? ()
#16 0x0000000000739480 in ?? ()
#17 0x00007fffe8c26000 in ?? ()
#18 0x00007ffff6bac746 in ?? () from /usr/lib/libQt5Qml.so.5
#19 0x00007ffff6c9759f in ?? () from /usr/lib/libQt5Qml.so.5
#20 0x00007ffff6c97aa6 in ?? () from /usr/lib/libQt5Qml.so.5
#21 0x00007ffff6c9fd79 in QQmlBinding::update(QFlags<QQmlPropertyPrivate::WriteFlag>) ()
   from /usr/lib/libQt5Qml.so.5
---Type <return> to continue, or q <return> to quit---
#22 0x00007ffff6ca916f in ?? () from /usr/lib/libQt5Qml.so.5
#23 0x00007ffff6c3235a in ?? () from /usr/lib/libQt5Qml.so.5
#24 0x00007ffff6c32ec1 in QQmlIncubationController::incubateFor(int) ()
   from /usr/lib/libQt5Qml.so.5
#25 0x00007ffff7b9ad58 in ?? () from /usr/lib/libQt5Quick.so.5
#26 0x00007ffff67c8023 in QObject::event(QEvent*) () from /usr/lib/libQt5Core.so.5
#27 0x00007ffff74adacc in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
#28 0x00007ffff74b2f10 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
#29 0x00007ffff6796d1b in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
   from /usr/lib/libQt5Core.so.5
#30 0x00007ffff67edf6d in QTimerInfoList::activateTimers() () from /usr/lib/libQt5Core.so.5
#31 0x00007ffff67ee3e9 in ?? () from /usr/lib/libQt5Core.so.5
#32 0x00007ffff520871d in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#33 0x00007ffff5208a08 in ?? () from /usr/lib/libglib-2.0.so.0
#34 0x00007ffff5208abc in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#35 0x00007ffff67ef077 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#36 0x00007ffff67947b2 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/libQt5Core.so.5
#37 0x00007ffff679c18c in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#38 0x000000000040c262 in main (argc=1, argv=<optimized out>) at ../src/main.cpp:73
(gdb) 

```

**Comment by xiangzhai** [comment]
Fixed ;-) https://github.com/xiangzhai/qwx/commit/842db10893b5af17a224a139f6e2c4964a214e72
